version: '3.8'

services:
    web:
        build: .
        ports:
            - "8000:80"
        volumes:
            - ./public:/var/www/html/public
        depends_on:
            - db

    db:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: 12348765
            MYSQL_DATABASE: blogTestTask_db

        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
